services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    env_file: .env
    ports:
      - "80:80" 
      - "443:443"
    volumes: 
      - web:/var/www/html
      - ./secrets/tls:/etc/nginx/secrets
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception-network

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    env_file: .env
    environment:
      - DOMAIN=$(wp_domain)
      - ADMIN_USER=$(wp_admin)
      - ADMIN_PASSWORD=$(wp_admin_password)
    volumes:
      - web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-network

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file: .env
    environment:
      - MYSQL_DATABASE=$()
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge

volumes:
  database:
  web:
